# environment variables
environment:
  GOPATH: c:\work\
  GOVERSION: 1.7

# clone path
clone_folder: c:\work\src\github.com\keybase\go-updater

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64

# scripts to run before build
before_build:

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:
  - go version
  - go build
  - go get github.com/stretchr/testify/assert
  - go get github.com/stretchr/testify/require
  - go get github.com/keybase/go-updater/test
  - dir %GOPATH%\bin\test.exe /s
  - go test -short -v ./...

# to disable automatic tests
test: off

# to disable deployment
deploy: off
